---
micronaut:
  application:
    name: hacker-news
  server:
    port: 8081

---
mongodb:
  uri: "mongodb://${MONGO_USER:hacker-user}:${MONGO_PASS:hackserpass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/hacker-news"
  database: "hacker-news"
---
news:
  api:
    version: "v1"

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
